name = "ping-udia-ca"
main = "dist/index.mjs"

account_id = ""
workers_dev = true
routes = [
  "ping.udia.ca",
  "ping.udia.ca/*"
]

compatibility_date = "2022-05-28"
compatibility_flags = []

[build]
command = "node build.js"

[miniflare]
kv_persist = true
cache_persist = true
durable_objects_persist = true
